server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8080
              predicates:
                - Path=/api/v1/auth/**

            - id: deck-service
              uri: http://deck-service:8080
              predicates:
                - Path=/api/v1/cards/**, /api/v1/decks/**

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never